"""add_verification_fields

Revision ID: d7cf8376a7f4
Revises: 3548b12ababd
Create Date: 2025-02-25 23:15:48.747373+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7cf8376a7f4'
down_revision = '3548b12ababd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
